// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) 2024 Western Digital Corporation or its affiliates.
 *
 * Authors: Damien Le Moal (damien.lemoal@wdc.com)
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <assert.h>

#include "ptio.h"

struct ptio_val_name {
	uint16_t	val;
	const char	*name;
};

/*
 * Sense keys.
 */
static struct ptio_val_name ptio_sense_keys[] =
{
	{ 0x00, "NO SENSE" },
	{ 0x01,	"RECOVERED ERROR" },
	{ 0x02,	"NOT READY" },
	{ 0x03,	"MEDIUM ERROR" },
	{ 0x04,	"HARDWARE ERROR" },
	{ 0x05,	"ILLEGAL REQUEST" },
	{ 0x06,	"UNIT ATTENTION" },
	{ 0x07,	"DATA PROTECT" },
	{ 0x08,	"BLANK CHECK" },
	{ 0x09,	"VENDOR SPECIFIC" },
	{ 0x0a,	"COPY ABORTED" },
	{ 0x0b,	"ABORTED COMMAND" },
	{ 0x0d,	"VOLUME OVERFLOW" },
	{ 0x0e,	"MISCOMPARE" },
	{ 0x0f,	"COMPLETED" },

	{ 0xffff, "unknown" },
};

/*
 * ASC / ASCQ.
 */
static struct ptio_val_name ptio_asc_ascq[] =
{
	{ 0x0000, "NO ADDITIONAL SENSE INFORMATION" },
	{ 0x0001, "FILEMARK DETECTED" },
	{ 0x0002, "END-OF-PARTITION/MEDIUM DETECTED" },
	{ 0x0003, "SETMARK DETECTED" },
	{ 0x0004, "BEGINNING-OF-PARTITION/MEDIUM DETECTED" },
	{ 0x0005, "END-OF-DATA DETECTED" },
	{ 0x0006, "I/O PROCESS TERMINATED" },
	{ 0x0007, "PROGRAMMABLE EARLY WARNING DETECTED" },
	{ 0x0011, "AUDIO PLAY OPERATION IN PROGRESS" },
	{ 0x0012, "AUDIO PLAY OPERATION PAUSED" },
	{ 0x0013, "AUDIO PLAY OPERATION SUCCESSFULLY COMPLETED" },
	{ 0x0014, "AUDIO PLAY OPERATION STOPPED DUE TO ERROR" },
	{ 0x0015, "NO CURRENT AUDIO STATUS TO RETURN" },
	{ 0x0016, "OPERATION IN PROGRESS" },
	{ 0x0017, "CLEANING REQUESTED" },
	{ 0x0018, "ERASE OPERATION IN PROGRESS" },
	{ 0x0019, "LOCATE OPERATION IN PROGRESS" },
	{ 0x001a, "REWIND OPERATION IN PROGRESS" },
	{ 0x001b, "SET CAPACITY OPERATION IN PROGRESS" },
	{ 0x001c, "VERIFY OPERATION IN PROGRESS" },
	{ 0x001d, "ATA PASS THROUGH INFORMATION AVAILABLE" },
	{ 0x001e, "CONFLICTING SA CREATION REQUEST" },
	{ 0x001f, "LOGICAL UNIT TRANSITIONING TO ANOTHER POWER CONDITION" },
	{ 0x0020, "EXTENDED COPY INFORMATION AVAILABLE" },
	{ 0x0021, "ATOMIC COMMAND ABORTED DUE TO ACA" },
	{ 0x0022, "DEFERRED MICROCODE IS PENDING" },
	{ 0x0023, "OVERLAPPING ATOMIC COMMAND IN PROGRESS" },

	{ 0x0100, "NO INDEX/SECTOR SIGNAL" },

	{ 0x0200, "NO SEEK COMPLETE" },

	{ 0x0300, "PERIPHERAL DEVICE WRITE FAULT" },
	{ 0x0301, "NO WRITE CURRENT" },
	{ 0x0302, "EXCESSIVE WRITE ERRORS" },

	{ 0x0400, "LOGICAL UNIT NOT READY, CAUSE NOT REPORTABLE" },
	{ 0x0401, "LOGICAL UNIT IS IN PROCESS OF BECOMING READY" },
	{ 0x0402, "LOGICAL UNIT NOT READY, INITIALIZING COMMAND REQUIRED" },
	{ 0x0403, "LOGICAL UNIT NOT READY, MANUAL INTERVENTION REQUIRED" },
	{ 0x0404, "LOGICAL UNIT NOT READY, FORMAT IN PROGRESS" },
	{ 0x0405, "LOGICAL UNIT NOT READY, REBUILD IN PROGRESS" },
	{ 0x0406, "LOGICAL UNIT NOT READY, RECALCULATION IN PROGRESS" },
	{ 0x0407, "LOGICAL UNIT NOT READY, OPERATION IN PROGRESS" },
	{ 0x0408, "LOGICAL UNIT NOT READY, LONG WRITE IN PROGRESS" },
	{ 0x0409, "LOGICAL UNIT NOT READY, SELF-TEST IN PROGRESS" },
	{ 0x040a, "LOGICAL UNIT NOT ACCESSIBLE, ASYMMETRIC ACCESS STATE TRANSITION" },
	{ 0x040b, "LOGICAL UNIT NOT ACCESSIBLE, TARGET PORT IN STANDBY STATE" },
	{ 0x040c, "LOGICAL UNIT NOT ACCESSIBLE, TARGET PORT IN UNAVAILABLE STATE" },
	{ 0x040d, "LOGICAL UNIT NOT READY, STRUCTURE CHECK REQUIRED" },
	{ 0x040e, "LOGICAL UNIT NOT READY, SECURITY SESSION IN PROGRESS" },
	{ 0x0410, "LOGICAL UNIT NOT READY, AUXILIARY MEMORY NOT ACCESSIBLE" },
	{ 0x0411, "LOGICAL UNIT NOT READY, NOTIFY (ENABLE SPINUP) REQUIRED" },
	{ 0x0412, "LOGICAL UNIT NOT READY, OFFLINE" },
	{ 0x0413, "LOGICAL UNIT NOT READY, SA CREATION IN PROGRESS" },
	{ 0x0414, "LOGICAL UNIT NOT READY, SPACE ALLOCATION IN PROGRESS" },
	{ 0x0415, "LOGICAL UNIT NOT READY, ROBOTICS DISABLED" },
	{ 0x0416, "LOGICAL UNIT NOT READY, CONFIGURATION REQUIRED" },
	{ 0x0417, "LOGICAL UNIT NOT READY, CALIBRATION REQUIRED" },
	{ 0x0418, "LOGICAL UNIT NOT READY, A DOOR IS OPEN" },
	{ 0x0419, "LOGICAL UNIT NOT READY, OPERATING IN SEQUENTIAL MODE" },
	{ 0x041a, "LOGICAL UNIT NOT READY, START STOP UNIT COMMAND IN PROGRESS" },
	{ 0x041b, "LOGICAL UNIT NOT READY, SANITIZE IN PROGRESS" },
	{ 0x041c, "LOGICAL UNIT NOT READY, ADDITIONAL POWER USE NOT YET GRANTED" },
	{ 0x041d, "LOGICAL UNIT NOT READY, CONFIGURATION IN PROGRESS" },
	{ 0x041e, "LOGICAL UNIT NOT READY, MICROCODE ACTIVATION REQUIRED" },
	{ 0x041f, "LOGICAL UNIT NOT READY, MICROCODE DOWNLOAD REQUIRED" },
	{ 0x0420, "LOGICAL UNIT NOT READY, LOGICAL UNIT RESET REQUIRED" },
	{ 0x0421, "LOGICAL UNIT NOT READY, HARD RESET REQUIRED" },
	{ 0x0422, "LOGICAL UNIT NOT READY, POWER CYCLE REQUIRED" },
	{ 0x0423, "LOGICAL UNIT NOT READY, AFFILIATION REQUIRED" },
	{ 0x0424, "DEPOPULATION IN PROGRESS" },
	{ 0x0425, "DEPOPULATION RESTORATION IN PROGRESS" },

	{ 0x0500, "LOGICAL UNIT DOES NOT RESPOND TO SELECTION" },

	{ 0x0600, "NO REFERENCE POSITION FOUND" },

	{ 0x0700, "MULTIPLE PERIPHERAL DEVICES SELECTED" },

	{ 0x0800, "LOGICAL UNIT COMMUNICATION FAILURE" },
	{ 0x0801, "LOGICAL UNIT COMMUNICATION TIME-OUT" },
	{ 0x0802, "LOGICAL UNIT COMMUNICATION PARITY ERROR" },
	{ 0x0803, "LOGICAL UNIT COMMUNICATION CRC ERROR (ULTRA-DMA/32)" },
	{ 0x0804, "UNREACHABLE COPY TARGET" },

	{ 0x0900, "TRACK FOLLOWING ERROR" },
	{ 0x0901, "TRACKING SERVO FAILURE" },
	{ 0x0902, "FOCUS SERVO FAILURE" },
	{ 0x0903, "SPINDLE SERVO FAILURE" },
	{ 0x0904, "HEAD SELECT FAULT" },
	{ 0x0905, "VIBRATION INDUCED TRACKING ERROR" },

	{ 0x0a00, "ERROR LOG OVERFLOW" },

	{ 0x0b00, "WARNING" },
	{ 0x0b01, "WARNING - SPECIFIED TEMPERATURE EXCEEDED" },
	{ 0x0b02, "WARNING - ENCLOSURE DEGRADED" },
	{ 0x0b03, "WARNING - BACKGROUND SELF-TEST FAILED" },
	{ 0x0b04, "WARNING - BACKGROUND PRE-SCAN DETECTED MEDIUM ERROR" },
	{ 0x0b05, "WARNING - BACKGROUND MEDIUM SCAN DETECTED MEDIUM ERROR" },
	{ 0x0b06, "WARNING - NON-VOLATILE CACHE NOW VOLATILE" },
	{ 0x0b07, "WARNING - DEGRADED POWER TO NON-VOLATILE CACHE" },
	{ 0x0b08, "WARNING - POWER LOSS EXPECTED" },
	{ 0x0b09, "WARNING - DEVICE STATISTICS NOTIFICATION ACTIVE" },
	{ 0x0b0a, "WARNING - HIGH CRITICAL TEMPERATURE LIMIT EXCEEDED" },
	{ 0x0b0b, "WARNING - LOW CRITICAL TEMPERATURE LIMIT EXCEEDED" },
	{ 0x0b0c, "WARNING - HIGH OPERATING TEMPERATURE LIMIT EXCEEDED" },
	{ 0x0b0d, "WARNING - LOW OPERATING TEMPERATURE LIMIT EXCEEDED" },
	{ 0x0b0e, "WARNING - HIGH CRITICAL HUMIDITY LIMIT EXCEEDED" },
	{ 0x0b0f, "WARNING - LOW CRITICAL HUMIDITY LIMIT EXCEEDED" },
	{ 0x0b10, "WARNING - HIGH OPERATING HUMIDITY LIMIT EXCEEDED" },
	{ 0x0b11, "WARNING - LOW OPERATING HUMIDITY LIMIT EXCEEDED" },
	{ 0x0b12, "WARNING - MICROCODE SECURITY AT RISK" },
	{ 0x0b13, "WARNING - MICROCODE DIGITAL SIGNATURE VALIDATION FAILURE" },
	{ 0x0b14, "WARNING - PHYSICAL ELEMENT STATUS CHANGE" },

	{ 0x0c00, "WRITE ERROR" },
	{ 0x0c01, "WRITE ERROR - RECOVERED WITH AUTO REALLOCATION" },
	{ 0x0c02, "WRITE ERROR - AUTO REALLOCATION FAILED" },
	{ 0x0c03, "WRITE ERROR - RECOMMEND REASSIGNMENT" },
	{ 0x0c04, "COMPRESSION CHECK MISCOMPARE ERROR" },
	{ 0x0c05, "DATA EXPANSION OCCURRED DURING COMPRESSION" },
	{ 0x0c06, "BLOCK NOT COMPRESSIBLE" },
	{ 0x0c07, "WRITE ERROR - RECOVERY NEEDED" },
	{ 0x0c08, "WRITE ERROR - RECOVERY FAILED" },
	{ 0x0c09, "WRITE ERROR - LOSS OF STREAMING" },
	{ 0x0c0a, "WRITE ERROR - PADDING BLOCKS ADDED" },
	{ 0x0c0b, "AUXILIARY MEMORY WRITE ERROR" },
	{ 0x0c0c, "WRITE ERROR - UNEXPECTED UNSOLICITED DATA" },
	{ 0x0c0d, "WRITE ERROR - NOT ENOUGH UNSOLICITED DATA" },
	{ 0x0c0e, "MULTIPLE WRITE ERRORS" },
	{ 0x0c0f, "DEFECTS IN ERROR WINDOW" },
	{ 0x0c10, "INCOMPLETE MULTIPLE ATOMIC WRITE OPERATIONS" },
	{ 0x0c11, "WRITE ERROR - RECOVERY SCAN NEEDED" },
	{ 0x0c12, "WRITE ERROR - INSUFFICIENT ZONE RESOURCES" },

	{ 0x0d00, "ERROR DETECTED BY THIRD PARTY TEMPORARY INITIATOR" },
	{ 0x0d01, "THIRD PARTY DEVICE FAILURE" },
	{ 0x0d02, "COPY TARGET DEVICE NOT REACHABLE" },
	{ 0x0d03, "INCORRECT COPY TARGET DEVICE TYPE" },
	{ 0x0d04, "COPY TARGET DEVICE DATA UNDERRUN" },
	{ 0x0d05, "COPY TARGET DEVICE DATA OVERRUN" },

	{ 0x0e00, "INVALID INFORMATION UNIT" },
	{ 0x0e01, "INFORMATION UNIT TOO SHORT" },
	{ 0x0e02, "INFORMATION UNIT TOO LONG" },
	{ 0x0e03, "INVALID FIELD IN COMMAND INFORMATION UNIT" },

	{ 0x1000, "ID CRC OR ECC ERROR" },
	{ 0x1001, "LOGICAL BLOCK GUARD CHECK FAILED" },
	{ 0x1002, "LOGICAL BLOCK APPLICATION TAG CHECK FAILED" },
	{ 0x1003, "LOGICAL BLOCK REFERENCE TAG CHECK FAILED" },
	{ 0x1004, "LOGICAL BLOCK PROTECTION ERROR ON RECOVER BUFFERED DATA" },
	{ 0x1005, "LOGICAL BLOCK PROTECTION METHOD ERROR" },

	{ 0x1100, "UNRECOVERED READ ERROR" },
	{ 0x1101, "READ RETRIES EXHAUSTED" },
	{ 0x1102, "ERROR TOO LONG TO CORRECT" },
	{ 0x1103, "MULTIPLE READ ERRORS" },
	{ 0x1104, "UNRECOVERED READ ERROR - AUTO REALLOCATE FAILED" },
	{ 0x1105, "L-EC UNCORRECTABLE ERROR" },
	{ 0x1106, "CIRC UNRECOVERED ERROR" },
	{ 0x1107, "DATA RE-SYNCHRONIZATION ERROR" },
	{ 0x1108, "INCOMPLETE BLOCK READ" },
	{ 0x1109, "NO GAP FOUND" },
	{ 0x110a, "MISCORRECTED ERROR" },
	{ 0x110b, "UNRECOVERED READ ERROR - RECOMMEND REASSIGNMENT" },
	{ 0x110c, "UNRECOVERED READ ERROR - RECOMMEND REWRITE THE DATA" },
	{ 0x110d, "DE-COMPRESSION CRC ERROR" },
	{ 0x110e, "CANNOT DECOMPRESS USING DECLARED ALGORITHM" },
	{ 0x110f, "ERROR READING UPC/EAN NUMBER" },
	{ 0x1110, "ERROR READING ISRC NUMBER" },
	{ 0x1111, "READ ERROR - LOSS OF STREAMING" },
	{ 0x1112, "AUXILIARY MEMORY READ ERROR" },
	{ 0x1113, "READ ERROR - FAILED RETRANSMISSION REQUEST" },
	{ 0x1114, "READ ERROR - LBA MARKED BAD BY APPLICATION CLIENT" },
	{ 0x1115, "WRITE AFTER SANITIZE REQUIRED" },

	{ 0x1200, "ADDRESS MARK NOT FOUND FOR ID FIELD" },

	{ 0x1300, "ADDRESS MARK NOT FOUND FOR DATA FIELD" },

	{ 0x1400, "RECORDED ENTITY NOT FOUND" },
	{ 0x1401, "RECORD NOT FOUND" },
	{ 0x1402, "FILEMARK OR SETMARK NOT FOUND" },
	{ 0x1403, "END-OF-DATA NOT FOUND" },
	{ 0x1404, "BLOCK SEQUENCE ERROR" },
	{ 0x1405, "RECORD NOT FOUND - RECOMMEND REASSIGNMENT" },
	{ 0x1406, "RECORD NOT FOUND - DATA AUTO-REALLOCATED" },
	{ 0x1407, "LOCATE OPERATION FAILURE" },

	{ 0x1500, "RANDOM POSITIONING ERROR" },
	{ 0x1501, "MECHANICAL POSITIONING ERROR" },
	{ 0x1502, "POSITIONING ERROR DETECTED BY READ OF MEDIUM" },

	{ 0x1600, "DATA SYNCHRONIZATION MARK ERROR" },
	{ 0x1601, "DATA SYNC ERROR - DATA REWRITTEN" },
	{ 0x1602, "DATA SYNC ERROR - RECOMMEND REWRITE" },
	{ 0x1603, "DATA SYNC ERROR - DATA AUTO-REALLOCATED" },
	{ 0x1604, "DATA SYNC ERROR - RECOMMEND REASSIGNMENT" },

	{ 0x1700, "RECOVERED DATA WITH NO ERROR CORRECTION APPLIED" },
	{ 0x1701, "RECOVERED DATA WITH RETRIES" },
	{ 0x1702, "RECOVERED DATA WITH POSITIVE HEAD OFFSET" },
	{ 0x1703, "RECOVERED DATA WITH NEGATIVE HEAD OFFSET" },
	{ 0x1704, "RECOVERED DATA WITH RETRIES AND/OR CIRC APPLIED" },
	{ 0x1705, "RECOVERED DATA USING PREVIOUS SECTOR ID" },
	{ 0x1706, "RECOVERED DATA WITHOUT ECC - DATA AUTO-REALLOCATED" },
	{ 0x1707, "RECOVERED DATA WITHOUT ECC - RECOMMEND REASSIGNMENT" },
	{ 0x1708, "RECOVERED DATA WITHOUT ECC - RECOMMEND REWRITE" },
	{ 0x1709, "RECOVERED DATA WITHOUT ECC - DATA REWRITTEN" },

	{ 0x1800, "RECOVERED DATA WITH ERROR CORRECTION APPLIED" },
	{ 0x1801, "RECOVERED DATA WITH ERROR CORR. & RETRIES APPLIED" },
	{ 0x1802, "RECOVERED DATA - DATA AUTO-REALLOCATED" },
	{ 0x1803, "RECOVERED DATA WITH CIRC" },
	{ 0x1804, "RECOVERED DATA WITH L-EC" },
	{ 0x1805, "RECOVERED DATA - RECOMMEND REASSIGNMENT" },
	{ 0x1806, "RECOVERED DATA - RECOMMEND REWRITE" },
	{ 0x1807, "RECOVERED DATA WITH ECC - DATA REWRITTEN" },
	{ 0x1808, "RECOVERED DATA WITH LINKING" },

	{ 0x1900, "DEFECT LIST ERROR" },
	{ 0x1901, "DEFECT LIST NOT AVAILABLE" },
	{ 0x1902, "DEFECT LIST ERROR IN PRIMARY LIST" },
	{ 0x1903, "DEFECT LIST ERROR IN GROWN LIST" },

	{ 0x1a00, "PARAMETER LIST LENGTH ERROR" },

	{ 0x1b00, "SYNCHRONOUS DATA TRANSFER ERROR" },

	{ 0x1c00, "DEFECT LIST NOT FOUND" },
	{ 0x1c01, "PRIMARY DEFECT LIST NOT FOUND" },
	{ 0x1c02, "GROWN DEFECT LIST NOT FOUND" },

	{ 0x1d00, "MISCOMPARE DURING VERIFY OPERATION" },
	{ 0x1d01, "MISCOMPARE VERIFY OF UNMAPPED LBA" },

	{ 0x1e00, "RECOVERED ID WITH ECC CORRECTION" },

	{ 0x1f00, "PARTIAL DEFECT LIST TRANSFER" },

	{ 0x2000, "INVALID COMMAND OPERATION CODE" },
	{ 0x2001, "ACCESS DENIED - INITIATOR PENDING-ENROLLED" },
	{ 0x2002, "ACCESS DENIED - NO ACCESS RIGHTS" },
	{ 0x2003, "ACCESS DENIED - INVALID MGMT ID KEY" },
	{ 0x2004, "ILLEGAL COMMAND WHILE IN WRITE CAPABLE STATE" },
	{ 0x2005, "Obsolete" },
	{ 0x2006, "ILLEGAL COMMAND WHILE IN EXPLICIT ADDRESS MODE" },
	{ 0x2007, "ILLEGAL COMMAND WHILE IN IMPLICIT ADDRESS MODE" },
	{ 0x2008, "ACCESS DENIED - ENROLLMENT CONFLICT" },
	{ 0x2009, "ACCESS DENIED - INVALID LU IDENTIFIER" },
	{ 0x200a, "ACCESS DENIED - INVALID PROXY TOKEN" },
	{ 0x200b, "ACCESS DENIED - ACL LUN CONFLICT" },
	{ 0x200c, "ILLEGAL COMMAND WHEN NOT IN APPEND-ONLY MODE" },
	{ 0x200d, "NOT AN ADMINISTRATIVE LOGICAL UNIT" },
	{ 0x200e, "NOT A SUBSIDIARY LOGICAL UNIT" },
	{ 0x200f, "NOT A CONGLOMERATE LOGICAL UNIT" },

	{ 0x2100, "LOGICAL BLOCK ADDRESS OUT OF RANGE" },
	{ 0x2101, "INVALID ELEMENT ADDRESS" },
	{ 0x2102, "INVALID ADDRESS FOR WRITE" },
	{ 0x2103, "INVALID WRITE CROSSING LAYER JUMP" },
	{ 0x2104, "UNALIGNED WRITE COMMAND" },
	{ 0x2105, "WRITE BOUNDARY VIOLATION" },
	{ 0x2106, "ATTEMPT TO READ INVALID DATA" },
	{ 0x2107, "READ BOUNDARY VIOLATION" },
	{ 0x2108, "MISALIGNED WRITE COMMAND" },
	{ 0x2109, "ATTEMPT TO ACCESS GAP ZONE" },

	{ 0x2200, "ILLEGAL FUNCTION (USE 20 00, 24 00, OR 26 00)" },

	{ 0x2300, "INVALID TOKEN OPERATION, CAUSE NOT REPORTABLE" },
	{ 0x2301, "INVALID TOKEN OPERATION, UNSUPPORTED TOKEN TYPE" },
	{ 0x2302, "INVALID TOKEN OPERATION, REMOTE TOKEN USAGE NOT SUPPORTED" },
	{ 0x2303, "INVALID TOKEN OPERATION, REMOTE ROD TOKEN CREATION NOT SUPPORTED" },
	{ 0x2304, "INVALID TOKEN OPERATION, TOKEN UNKNOWN" },
	{ 0x2305, "INVALID TOKEN OPERATION, TOKEN CORRUPT" },
	{ 0x2306, "INVALID TOKEN OPERATION, TOKEN REVOKED" },
	{ 0x2307, "INVALID TOKEN OPERATION, TOKEN EXPIRED" },
	{ 0x2308, "INVALID TOKEN OPERATION, TOKEN CANCELLED" },
	{ 0x2309, "INVALID TOKEN OPERATION, TOKEN DELETED" },
	{ 0x230a, "INVALID TOKEN OPERATION, INVALID TOKEN LENGTH" },

	{ 0x2400, "INVALID FIELD IN CDB" },
	{ 0x2401, "CDB DECRYPTION ERROR" },
	{ 0x2402, "Obsolete" },
	{ 0x2403, "Obsolete" },
	{ 0x2404, "SECURITY AUDIT VALUE FROZEN" },
	{ 0x2405, "SECURITY WORKING KEY FROZEN" },
	{ 0x2406, "NONCE NOT UNIQUE" },
	{ 0x2407, "NONCE TIMESTAMP OUT OF RANGE" },
	{ 0x2408, "INVALID XCDB" },
	{ 0x2409, "INVALID FAST FORMAT" },

	{ 0x2500, "LOGICAL UNIT NOT SUPPORTED" },

	{ 0x2600, "INVALID FIELD IN PARAMETER LIST" },
	{ 0x2601, "PARAMETER NOT SUPPORTED" },
	{ 0x2602, "PARAMETER VALUE INVALID" },
	{ 0x2603, "THRESHOLD PARAMETERS NOT SUPPORTED" },
	{ 0x2604, "INVALID RELEASE OF PERSISTENT RESERVATION" },
	{ 0x2605, "DATA DECRYPTION ERROR" },
	{ 0x2606, "TOO MANY TARGET DESCRIPTORS" },
	{ 0x2607, "UNSUPPORTED TARGET DESCRIPTOR TYPE CODE" },
	{ 0x2608, "TOO MANY SEGMENT DESCRIPTORS" },
	{ 0x2609, "UNSUPPORTED SEGMENT DESCRIPTOR TYPE CODE" },
	{ 0x260a, "UNEXPECTED INEXACT SEGMENT" },
	{ 0x260b, "INLINE DATA LENGTH EXCEEDED" },
	{ 0x260c, "INVALID OPERATION FOR COPY SOURCE OR DESTINATION" },
	{ 0x260d, "COPY SEGMENT GRANULARITY VIOLATION" },
	{ 0x260e, "INVALID PARAMETER WHILE PORT IS ENABLED" },
	{ 0x260f, "INVALID DATA-OUT BUFFER INTEGRITY CHECK VALUE" },
	{ 0x2610, "DATA DECRYPTION KEY FAIL LIMIT REACHED" },
	{ 0x2611, "INCOMPLETE KEY-ASSOCIATED DATA SET" },
	{ 0x2612, "VENDOR SPECIFIC KEY REFERENCE NOT FOUND" },
	{ 0x2613, "APPLICATION TAG MODE PAGE IS INVALID" },
	{ 0x2614, "TAPE STREAM MIRRORING PREVENTED" },
	{ 0x2615, "COPY SOURCE OR COPY DESTINATION NOT AUTHORIZED" },
	{ 0x2616, "FAST COPY NOT POSSIBLE" },

	{ 0x2700, "WRITE PROTECTED" },
	{ 0x2701, "HARDWARE WRITE PROTECTED" },
	{ 0x2702, "LOGICAL UNIT SOFTWARE WRITE PROTECTED" },
	{ 0x2703, "ASSOCIATED WRITE PROTECT" },
	{ 0x2704, "PERSISTENT WRITE PROTECT" },
	{ 0x2705, "PERMANENT WRITE PROTECT" },
	{ 0x2706, "CONDITIONAL WRITE PROTECT" },
	{ 0x2707, "SPACE ALLOCATION FAILED WRITE PROTECT" },
	{ 0x2708, "ZONE IS READ ONLY" },

	{ 0x2800, "NOT READY TO READY CHANGE, MEDIUM MAY HAVE CHANGED" },
	{ 0x2801, "IMPORT OR EXPORT ELEMENT ACCESSED" },
	{ 0x2802, "FORMAT-LAYER MAY HAVE CHANGED" },
	{ 0x2803, "IMPORT/EXPORT ELEMENT ACCESSED, MEDIUM CHANGED" },

	{ 0x2900, "POWER ON, RESET, OR BUS DEVICE RESET OCCURRED" },
	{ 0x2901, "POWER ON OCCURRED" },
	{ 0x2902, "SCSI BUS RESET OCCURRED" },
	{ 0x2903, "BUS DEVICE RESET FUNCTION OCCURRED" },
	{ 0x2904, "DEVICE INTERNAL RESET" },
	{ 0x2905, "TRANSCEIVER MODE CHANGED TO SINGLE-ENDED" },
	{ 0x2906, "TRANSCEIVER MODE CHANGED TO LVD" },
	{ 0x2907, "I_T NEXUS LOSS OCCURRED" },

	{ 0x2a00, "PARAMETERS CHANGED" },
	{ 0x2a01, "MODE PARAMETERS CHANGED" },
	{ 0x2a02, "LOG PARAMETERS CHANGED" },
	{ 0x2a03, "RESERVATIONS PREEMPTED" },
	{ 0x2a04, "RESERVATIONS RELEASED" },
	{ 0x2a05, "REGISTRATIONS PREEMPTED" },
	{ 0x2a06, "ASYMMETRIC ACCESS STATE CHANGED" },
	{ 0x2a07, "IMPLICIT ASYMMETRIC ACCESS STATE TRANSITION FAILED" },
	{ 0x2a08, "PRIORITY CHANGED" },
	{ 0x2a09, "CAPACITY DATA HAS CHANGED" },
	{ 0x2a0a, "ERROR HISTORY I_T NEXUS CLEARED" },
	{ 0x2a0b, "ERROR HISTORY SNAPSHOT RELEASED" },
	{ 0x2a0c, "ERROR RECOVERY ATTRIBUTES HAVE CHANGED" },
	{ 0x2a0d, "DATA ENCRYPTION CAPABILITIES CHANGED" },
	{ 0x2a10, "TIMESTAMP CHANGED" },
	{ 0x2a11, "DATA ENCRYPTION PARAMETERS CHANGED BY ANOTHER I_T NEXUS" },
	{ 0x2a12, "DATA ENCRYPTION PARAMETERS CHANGED BY VENDOR SPECIFIC EVENT" },
	{ 0x2a13, "DATA ENCRYPTION KEY INSTANCE COUNTER HAS CHANGED" },
	{ 0x2a14, "SA CREATION CAPABILITIES DATA HAS CHANGED" },
	{ 0x2a15, "MEDIUM REMOVAL PREVENTION PREEMPTED" },
	{ 0x2a16, "ZONE RESET WRITE POINTER RECOMMENDED" },

	{ 0x2b00, "COPY CANNOT EXECUTE SINCE HOST CANNOT DISCONNECT" },

	{ 0x2c00, "COMMAND SEQUENCE ERROR" },
	{ 0x2c01, "TOO MANY WINDOWS SPECIFIED {%" },
	{ 0x2c02, "INVALID COMBINATION OF WINDOWS SPECIFIED {%" },
	{ 0x2c03, "CURRENT PROGRAM AREA IS NOT EMPTY" },
	{ 0x2c04, "CURRENT PROGRAM AREA IS EMPTY" },
	{ 0x2c05, "ILLEGAL POWER CONDITION REQUEST" },
	{ 0x2c06, "PERSISTENT PREVENT CONFLICT" },
	{ 0x2c07, "PREVIOUS BUSY STATUS" },
	{ 0x2c08, "PREVIOUS TASK SET FULL STATUS" },
	{ 0x2c09, "PREVIOUS RESERVATION CONFLICT STATUS" },
	{ 0x2c0a, "PARTITION OR COLLECTION CONTAINS USER OBJECTS" },
	{ 0x2c0b, "NOT RESERVED" },
	{ 0x2c0c, "ORWRITE GENERATION DOES NOT MATCH" },
	{ 0x2c0d, "RESET WRITE POINTER NOT ALLOWED" },
	{ 0x2c0e, "ZONE IS OFFLINE" },
	{ 0x2c0f, "STREAM NOT OPEN" },
	{ 0x2c10, "UNWRITTEN DATA IN ZONE" },
	{ 0x2c11, "DESCRIPTOR FORMAT SENSE DATA REQUIRED" },
	{ 0x2c12, "ZONE IS INACTIVE" },
	{ 0x2c13, "WELL KNOWN LOGICAL UNIT ACCESS REQUIRED" },

	{ 0x2d00, "OVERWRITE ERROR ON UPDATE IN PLACE" },

	{ 0x2e00, "INSUFFICIENT TIME FOR OPERATION" },
	{ 0x2e01, "COMMAND TIMEOUT BEFORE PROCESSING" },
	{ 0x2e02, "COMMAND TIMEOUT DURING PROCESSING" },
	{ 0x2e03, "COMMAND TIMEOUT DURING PROCESSING DUE TO ERROR RECOVERY" },

	{ 0x2f00, "COMMANDS CLEARED BY ANOTHER INITIATOR" },
	{ 0x2f01, "COMMANDS CLEARED BY POWER LOSS NOTIFICATION" },
	{ 0x2f02, "COMMANDS CLEARED BY DEVICE SERVER" },
	{ 0x2f03, "SOME COMMANDS CLEARED BY QUEUING LAYER EVENT" },

	{ 0x3000, "INCOMPATIBLE MEDIUM INSTALLED" },
	{ 0x3001, "CANNOT READ MEDIUM - UNKNOWN FORMAT" },
	{ 0x3002, "CANNOT READ MEDIUM - INCOMPATIBLE FORMAT" },
	{ 0x3003, "CLEANING CARTRIDGE INSTALLED" },
	{ 0x3004, "CANNOT WRITE MEDIUM - UNKNOWN FORMAT" },
	{ 0x3005, "CANNOT WRITE MEDIUM - INCOMPATIBLE FORMAT" },
	{ 0x3006, "CANNOT FORMAT MEDIUM - INCOMPATIBLE MEDIUM" },
	{ 0x3007, "CLEANING FAILURE" },
	{ 0x3008, "CANNOT WRITE - APPLICATION CODE MISMATCH" },
	{ 0x3009, "CURRENT SESSION NOT FIXATED FOR APPEND" },
	{ 0x300a, "CLEANING REQUEST REJECTED" },
	{ 0x300c, "WORM MEDIUM - OVERWRITE ATTEMPTED" },
	{ 0x300d, "WORM MEDIUM - INTEGRITY CHECK" },
	{ 0x3010, "MEDIUM NOT FORMATTED" },
	{ 0x3011, "INCOMPATIBLE VOLUME TYPE" },
	{ 0x3012, "INCOMPATIBLE VOLUME QUALIFIER" },
	{ 0x3013, "CLEANING VOLUME EXPIRED" },

	{ 0x3100, "MEDIUM FORMAT CORRUPTED" },
	{ 0x3101, "FORMAT COMMAND FAILED" },
	{ 0x3102, "ZONED FORMATTING FAILED DUE TO SPARE LINKING" },
	{ 0x3103, "SANITIZE COMMAND FAILED" },
	{ 0x3104, "DEPOPULATION FAILED" },
	{ 0x3105, "DEPOPULATION RESTORATION FAILED" },

	{ 0x3200, "NO DEFECT SPARE LOCATION AVAILABLE" },
	{ 0x3201, "DEFECT LIST UPDATE FAILURE" },

	{ 0x3300, "TAPE LENGTH ERROR" },

	{ 0x3400, "ENCLOSURE FAILURE" },

	{ 0x3500, "ENCLOSURE SERVICES FAILURE" },
	{ 0x3501, "UNSUPPORTED ENCLOSURE FUNCTION" },
	{ 0x3502, "ENCLOSURE SERVICES UNAVAILABLE" },
	{ 0x3503, "ENCLOSURE SERVICES TRANSFER FAILURE" },
	{ 0x3504, "ENCLOSURE SERVICES TRANSFER REFUSED" },
	{ 0x3505, "ENCLOSURE SERVICES CHECKSUM ERROR" },

	{ 0x3600, "RIBBON, INK, OR TONER FAILURE {%" },

	{ 0x3700, "ROUNDED PARAMETER" },

	{ 0x3800, "EVENT STATUS NOTIFICATION" },
	{ 0x3802, "ESN - POWER MANAGEMENT CLASS EVENT" },
	{ 0x3804, "ESN - MEDIA CLASS EVENT" },
	{ 0x3806, "ESN - DEVICE BUSY CLASS EVENT" },
	{ 0x3807, "THIN PROVISIONING SOFT THRESHOLD REACHED" },
	{ 0x3808, "DEPOPULATION INTERRUPTED" },
	{ 0x3809, "DEPOPULATION RESTORATION INTERRUPTED" },

	{ 0x3900, "SAVING PARAMETERS NOT SUPPORTED" },

	{ 0x3a00, "MEDIUM NOT PRESENT" },
	{ 0x3a01, "MEDIUM NOT PRESENT - TRAY CLOSED" },
	{ 0x3a02, "MEDIUM NOT PRESENT - TRAY OPEN" },
	{ 0x3a03, "MEDIUM NOT PRESENT - LOADABLE" },
	{ 0x3a04, "MEDIUM NOT PRESENT - MEDIUM AUXILIARY MEMORY ACCESSIBLE" },

	{ 0x3b00, "SEQUENTIAL POSITIONING ERROR" },
	{ 0x3b01, "TAPE POSITION ERROR AT BEGINNING-OF-MEDIUM" },
	{ 0x3b02, "TAPE POSITION ERROR AT END-OF-MEDIUM" },
	{ 0x3b03, "TAPE OR ELECTRONIC VERTICAL FORMS UNIT NOT READY {%" },
	{ 0x3b04, "SLEW FAILURE {%" },
	{ 0x3b05, "PAPER JAM {%" },
	{ 0x3b06, "FAILED TO SENSE TOP-OF-FORM {%" },
	{ 0x3b07, "FAILED TO SENSE BOTTOM-OF-FORM {%" },
	{ 0x3b08, "REPOSITION ERROR {%" },
	{ 0x3b09, "READ PAST END OF MEDIUM {%" },
	{ 0x3b0a, "READ PAST BEGINNING OF MEDIUM {%" },
	{ 0x3b0b, "POSITION PAST END OF MEDIUM {%" },
	{ 0x3b0c, "POSITION PAST BEGINNING OF MEDIUM" },
	{ 0x3b0d, "MEDIUM DESTINATION ELEMENT FULL" },
	{ 0x3b0e, "MEDIUM SOURCE ELEMENT EMPTY" },
	{ 0x3b0f, "END OF MEDIUM REACHED" },
	{ 0x3b11, "MEDIUM MAGAZINE NOT ACCESSIBLE" },
	{ 0x3b12, "MEDIUM MAGAZINE REMOVED" },
	{ 0x3b13, "MEDIUM MAGAZINE INSERTED" },
	{ 0x3b14, "MEDIUM MAGAZINE LOCKED" },
	{ 0x3b15, "MEDIUM MAGAZINE UNLOCKED" },
	{ 0x3b16, "MECHANICAL POSITIONING OR CHANGER ERROR" },
	{ 0x3b17, "READ PAST END OF USER OBJECT" },
	{ 0x3b18, "ELEMENT DISABLED" },
	{ 0x3b19, "ELEMENT ENABLED" },
	{ 0x3b1a, "DATA TRANSFER DEVICE REMOVED" },
	{ 0x3b1b, "DATA TRANSFER DEVICE INSERTED" },
	{ 0x3b1c, "TOO MANY LOGICAL OBJECTS ON PARTITION TO SUPPORT OPERATION" },
	{ 0x3b20, "ELEMENT STATIC INFORMATION CHANGED" },

	{ 0x3d00, "INVALID BITS IN IDENTIFY MESSAGE" },

	{ 0x3e00, "LOGICAL UNIT HAS NOT SELF-CONFIGURED YET" },
	{ 0x3e01, "LOGICAL UNIT FAILURE" },
	{ 0x3e02, "TIMEOUT ON LOGICAL UNIT" },
	{ 0x3e03, "LOGICAL UNIT FAILED SELF-TEST" },
	{ 0x3e04, "LOGICAL UNIT UNABLE TO UPDATE SELF-TEST LOG" },

	{ 0x3f00, "TARGET OPERATING CONDITIONS HAVE CHANGED" },
	{ 0x3f01, "MICROCODE HAS BEEN CHANGED" },
	{ 0x3f02, "CHANGED OPERATING DEFINITION" },
	{ 0x3f03, "INQUIRY DATA HAS CHANGED" },
	{ 0x3f04, "COMPONENT DEVICE ATTACHED" },
	{ 0x3f05, "DEVICE IDENTIFIER CHANGED" },
	{ 0x3f06, "REDUNDANCY GROUP CREATED OR MODIFIED" },
	{ 0x3f07, "REDUNDANCY GROUP DELETED" },
	{ 0x3f08, "SPARE CREATED OR MODIFIED" },
	{ 0x3f09, "SPARE DELETED" },
	{ 0x3f0a, "VOLUME SET CREATED OR MODIFIED" },
	{ 0x3f0b, "VOLUME SET DELETED" },
	{ 0x3f0c, "VOLUME SET DEASSIGNED" },
	{ 0x3f0d, "VOLUME SET REASSIGNED" },
	{ 0x3f0e, "REPORTED LUNS DATA HAS CHANGED" },
	{ 0x3f0f, "ECHO BUFFER OVERWRITTEN" },
	{ 0x3f10, "MEDIUM LOADABLE" },
	{ 0x3f11, "MEDIUM AUXILIARY MEMORY ACCESSIBLE" },
	{ 0x3f12, "iSCSI IP ADDRESS ADDED" },
	{ 0x3f13, "iSCSI IP ADDRESS REMOVED" },
	{ 0x3f14, "iSCSI IP ADDRESS CHANGED" },
	{ 0x3f15, "INSPECT REFERRALS SENSE DESCRIPTORS" },
	{ 0x3f16, "MICROCODE HAS BEEN CHANGED WITHOUT RESET" },
	{ 0x3f17, "ZONE TRANSITION TO FULL" },
	{ 0x3f18, "BIND COMPLETED" },
	{ 0x3f19, "BIND REDIRECTED" },
	{ 0x3f1a, "SUBSIDIARY BINDING CHANGED" },

	{ 0x4000, "RAM FAILURE (SHOULD USE 40 NN)" },

	{ 0x4100, "DATA PATH FAILURE (SHOULD USE 40 NN)" },

	{ 0x4200, "POWER-ON OR SELF-TEST FAILURE (SHOULD USE 40 NN)" },

	{ 0x4300, "MESSAGE ERROR" },

	{ 0x4400, "INTERNAL TARGET FAILURE" },
	{ 0x4401, "PERSISTENT RESERVATION INFORMATION LOST" },
	{ 0x4471, "ATA DEVICE FAILED SET FEATURES" },

	{ 0x4500, "SELECT OR RESELECT FAILURE" },

	{ 0x4600, "UNSUCCESSFUL SOFT RESET" },

	{ 0x4700, "SCSI PARITY ERROR" },
	{ 0x4701, "DATA PHASE CRC ERROR DETECTED" },
	{ 0x4702, "SCSI PARITY ERROR DETECTED DURING ST DATA PHASE" },
	{ 0x4703, "INFORMATION UNIT iuCRC ERROR DETECTED" },
	{ 0x4704, "ASYNCHRONOUS INFORMATION PROTECTION ERROR DETECTED" },
	{ 0x4705, "PROTOCOL SERVICE CRC ERROR" },
	{ 0x4706, "PHY TEST FUNCTION IN PROGRESS" },
	{ 0x477f, "SOME COMMANDS CLEARED BY ISCSI PROTOCOL EVENT" },

	{ 0x4800, "INITIATOR DETECTED ERROR MESSAGE RECEIVED" },

	{ 0x4900, "INVALID MESSAGE ERROR" },

	{ 0x4a00, "COMMAND PHASE ERROR" },

	{ 0x4b00, "DATA PHASE ERROR" },
	{ 0x4b01, "INVALID TARGET PORT TRANSFER TAG RECEIVED" },
	{ 0x4b02, "TOO MUCH WRITE DATA" },
	{ 0x4b03, "ACK/NAK TIMEOUT" },
	{ 0x4b04, "NAK RECEIVED" },
	{ 0x4b05, "DATA OFFSET ERROR" },
	{ 0x4b06, "INITIATOR RESPONSE TIMEOUT" },
	{ 0x4b07, "CONNECTION LOST" },
	{ 0x4b08, "DATA-IN BUFFER OVERFLOW - DATA BUFFER SIZE" },
	{ 0x4b09, "DATA-IN BUFFER OVERFLOW - DATA BUFFER DESCRIPTOR AREA" },
	{ 0x4b0a, "DATA-IN BUFFER ERROR" },
	{ 0x4b0b, "DATA-OUT BUFFER OVERFLOW - DATA BUFFER SIZE" },
	{ 0x4b0c, "DATA-OUT BUFFER OVERFLOW - DATA BUFFER DESCRIPTOR AREA" },
	{ 0x4b0d, "DATA-OUT BUFFER ERROR" },
	{ 0x4b0e, "PCIE FABRIC ERROR" },
	{ 0x4b0f, "PCIE COMPLETION TIMEOUT" },
	{ 0x4b10, "PCIE COMPLETER ABORT" },
	{ 0x4b11, "PCIE POISONED TLP RECEIVED" },
	{ 0x4b12, "PCIE ECRC CHECK FAILED" },
	{ 0x4b13, "PCIE UNSUPPORTED REQUEST" },
	{ 0x4b14, "PCIE ACS VIOLATION" },
	{ 0x4b15, "PCIE TLP PREFIX BLOCKED" },

	{ 0x4c00, "LOGICAL UNIT FAILED SELF-CONFIGURATION" },

	{ 0x4e00, "OVERLAPPED COMMANDS ATTEMPTED" },

	{ 0x5000, "WRITE APPEND ERROR" },
	{ 0x5001, "WRITE APPEND POSITION ERROR" },
	{ 0x5002, "POSITION ERROR RELATED TO TIMING" },

	{ 0x5100, "ERASE FAILURE" },
	{ 0x5101, "ERASE FAILURE - INCOMPLETE ERASE OPERATION DETECTED" },

	{ 0x5200, "CARTRIDGE FAULT" },

	{ 0x5300, "MEDIA LOAD OR EJECT FAILED" },
	{ 0x5301, "UNLOAD TAPE FAILURE" },
	{ 0x5302, "MEDIUM REMOVAL PREVENTED" },
	{ 0x5303, "MEDIUM REMOVAL PREVENTED BY DATA TRANSFER ELEMENT" },
	{ 0x5304, "MEDIUM THREAD OR UNTHREAD FAILURE" },
	{ 0x5305, "VOLUME IDENTIFIER INVALID" },
	{ 0x5306, "VOLUME IDENTIFIER MISSING" },
	{ 0x5307, "DUPLICATE VOLUME IDENTIFIER" },
	{ 0x5308, "ELEMENT STATUS UNKNOWN" },
	{ 0x5309, "DATA TRANSFER DEVICE ERROR - LOAD FAILED" },
	{ 0x530a, "DATA TRANSFER DEVICE ERROR - UNLOAD FAILED" },
	{ 0x530b, "DATA TRANSFER DEVICE ERROR - UNLOAD MISSING" },
	{ 0x530c, "DATA TRANSFER DEVICE ERROR - EJECT FAILED" },
	{ 0x530d, "DATA TRANSFER DEVICE ERROR - LIBRARY COMMUNICATION FAILED" },

	{ 0x5400, "SCSI TO HOST SYSTEM INTERFACE FAILURE" },

	{ 0x5500, "SYSTEM RESOURCE FAILURE" },
	{ 0x5501, "SYSTEM BUFFER FULL" },
	{ 0x5502, "INSUFFICIENT RESERVATION RESOURCES" },
	{ 0x5503, "INSUFFICIENT RESOURCES" },
	{ 0x5504, "INSUFFICIENT REGISTRATION RESOURCES" },
	{ 0x5505, "INSUFFICIENT ACCESS CONTROL RESOURCES" },
	{ 0x5506, "AUXILIARY MEMORY OUT OF SPACE" },
	{ 0x5507, "QUOTA ERROR" },
	{ 0x5508, "MAXIMUM NUMBER OF SUPPLEMENTAL DECRYPTION KEYS EXCEEDED" },
	{ 0x5509, "MEDIUM AUXILIARY MEMORY NOT ACCESSIBLE" },
	{ 0x550a, "DATA CURRENTLY UNAVAILABLE" },
	{ 0x550b, "INSUFFICIENT POWER FOR OPERATION" },
	{ 0x550c, "INSUFFICIENT RESOURCES TO CREATE ROD" },
	{ 0x550d, "INSUFFICIENT RESOURCES TO CREATE ROD TOKEN" },
	{ 0x550e, "INSUFFICIENT ZONE RESOURCES" },
	{ 0x550f, "INSUFFICIENT ZONE RESOURCES TO COMPLETE WRITE" },
	{ 0x5510, "MAXIMUM NUMBER OF STREAMS OPEN" },
	{ 0x5511, "INSUFFICIENT RESOURCES TO BIND" },

	{ 0x5700, "UNABLE TO RECOVER TABLE-OF-CONTENTS" },

	{ 0x5800, "GENERATION DOES NOT EXIST" },

	{ 0x5900, "UPDATED BLOCK READ" },

	{ 0x5a00, "OPERATOR REQUEST OR STATE CHANGE INPUT" },
	{ 0x5a01, "OPERATOR MEDIUM REMOVAL REQUEST" },
	{ 0x5a02, "OPERATOR SELECTED WRITE PROTECT" },
	{ 0x5a03, "OPERATOR SELECTED WRITE PERMIT" },

	{ 0x5b00, "LOG EXCEPTION" },
	{ 0x5b01, "THRESHOLD CONDITION MET" },
	{ 0x5b02, "LOG COUNTER AT MAXIMUM" },
	{ 0x5b03, "LOG LIST CODES EXHAUSTED" },

	{ 0x5c00, "RPL STATUS CHANGE" },
	{ 0x5c01, "SPINDLES SYNCHRONIZED" },
	{ 0x5c02, "SPINDLES NOT SYNCHRONIZED" },

	{ 0x5d00, "FAILURE PREDICTION THRESHOLD EXCEEDED" },
	{ 0x5d01, "MEDIA FAILURE PREDICTION THRESHOLD EXCEEDED" },
	{ 0x5d02, "LOGICAL UNIT FAILURE PREDICTION THRESHOLD EXCEEDED" },
	{ 0x5d03, "SPARE AREA EXHAUSTION PREDICTION THRESHOLD EXCEEDED" },
	{ 0x5d10, "HARDWARE IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d11, "HARDWARE IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d12, "HARDWARE IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d13, "HARDWARE IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d14, "HARDWARE IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d15, "HARDWARE IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d16, "HARDWARE IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d17, "HARDWARE IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d18, "HARDWARE IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d19, "HARDWARE IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d1a, "HARDWARE IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d1b, "HARDWARE IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d1c, "HARDWARE IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d1d, "HARDWARE IMPENDING FAILURE POWER LOSS PROTECTION CIRCUIT" },
	{ 0x5d20, "CONTROLLER IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d21, "CONTROLLER IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d22, "CONTROLLER IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d23, "CONTROLLER IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d24, "CONTROLLER IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d25, "CONTROLLER IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d26, "CONTROLLER IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d27, "CONTROLLER IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d28, "CONTROLLER IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d29, "CONTROLLER IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d2a, "CONTROLLER IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d2b, "CONTROLLER IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d2c, "CONTROLLER IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d30, "DATA CHANNEL IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d31, "DATA CHANNEL IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d32, "DATA CHANNEL IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d33, "DATA CHANNEL IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d34, "DATA CHANNEL IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d35, "DATA CHANNEL IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d36, "DATA CHANNEL IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d37, "DATA CHANNEL IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d38, "DATA CHANNEL IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d39, "DATA CHANNEL IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d3a, "DATA CHANNEL IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d3b, "DATA CHANNEL IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d3c, "DATA CHANNEL IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d40, "SERVO IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d41, "SERVO IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d42, "SERVO IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d43, "SERVO IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d44, "SERVO IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d45, "SERVO IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d46, "SERVO IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d47, "SERVO IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d48, "SERVO IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d49, "SERVO IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d4a, "SERVO IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d4b, "SERVO IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d4c, "SERVO IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d50, "SPINDLE IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d51, "SPINDLE IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d52, "SPINDLE IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d53, "SPINDLE IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d54, "SPINDLE IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d55, "SPINDLE IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d56, "SPINDLE IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d57, "SPINDLE IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d58, "SPINDLE IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d59, "SPINDLE IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d5a, "SPINDLE IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d5b, "SPINDLE IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d5c, "SPINDLE IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d60, "FIRMWARE IMPENDING FAILURE GENERAL HARD DRIVE FAILURE" },
	{ 0x5d61, "FIRMWARE IMPENDING FAILURE DRIVE ERROR RATE TOO HIGH" },
	{ 0x5d62, "FIRMWARE IMPENDING FAILURE DATA ERROR RATE TOO HIGH" },
	{ 0x5d63, "FIRMWARE IMPENDING FAILURE SEEK ERROR RATE TOO HIGH" },
	{ 0x5d64, "FIRMWARE IMPENDING FAILURE TOO MANY BLOCK REASSIGNS" },
	{ 0x5d65, "FIRMWARE IMPENDING FAILURE ACCESS TIMES TOO HIGH" },
	{ 0x5d66, "FIRMWARE IMPENDING FAILURE START UNIT TIMES TOO HIGH" },
	{ 0x5d67, "FIRMWARE IMPENDING FAILURE CHANNEL PARAMETRICS" },
	{ 0x5d68, "FIRMWARE IMPENDING FAILURE CONTROLLER DETECTED" },
	{ 0x5d69, "FIRMWARE IMPENDING FAILURE THROUGHPUT PERFORMANCE" },
	{ 0x5d6a, "FIRMWARE IMPENDING FAILURE SEEK TIME PERFORMANCE" },
	{ 0x5d6b, "FIRMWARE IMPENDING FAILURE SPIN-UP RETRY COUNT" },
	{ 0x5d6c, "FIRMWARE IMPENDING FAILURE DRIVE CALIBRATION RETRY COUNT" },
	{ 0x5d73, "MEDIA IMPENDING FAILURE ENDURANCE LIMIT MET" },
	{ 0x5dff, "FAILURE PREDICTION THRESHOLD EXCEEDED (FALSE)" },

	{ 0x5e00, "LOW POWER CONDITION ON" },
	{ 0x5e01, "IDLE CONDITION ACTIVATED BY TIMER" },
	{ 0x5e02, "STANDBY CONDITION ACTIVATED BY TIMER" },
	{ 0x5e03, "IDLE CONDITION ACTIVATED BY COMMAND" },
	{ 0x5e04, "STANDBY CONDITION ACTIVATED BY COMMAND" },
	{ 0x5e05, "IDLE_B CONDITION ACTIVATED BY TIMER" },
	{ 0x5e06, "IDLE_B CONDITION ACTIVATED BY COMMAND" },
	{ 0x5e07, "IDLE_C CONDITION ACTIVATED BY TIMER" },
	{ 0x5e08, "IDLE_C CONDITION ACTIVATED BY COMMAND" },
	{ 0x5e09, "STANDBY_Y CONDITION ACTIVATED BY TIMER" },
	{ 0x5e0a, "STANDBY_Y CONDITION ACTIVATED BY COMMAND" },
	{ 0x5e41, "POWER STATE CHANGE TO ACTIVE" },
	{ 0x5e42, "POWER STATE CHANGE TO IDLE" },
	{ 0x5e43, "POWER STATE CHANGE TO STANDBY" },
	{ 0x5e45, "POWER STATE CHANGE TO SLEEP" },
	{ 0x5e47, "POWER STATE CHANGE TO DEVICE CONTROL" },

	{ 0x6000, "LAMP FAILURE {%" },

	{ 0x6100, "VIDEO ACQUISITION ERROR {%" },
	{ 0x6101, "UNABLE TO ACQUIRE VIDEO {%" },
	{ 0x6102, "OUT OF FOCUS {%" },

	{ 0x6200, "SCAN HEAD POSITIONING ERROR {%" },

	{ 0x6300, "END OF USER AREA ENCOUNTERED ON THIS TRACK" },
	{ 0x6301, "PACKET DOES NOT FIT IN AVAILABLE SPACE" },

	{ 0x6400, "ILLEGAL MODE FOR THIS TRACK" },
	{ 0x6401, "INVALID PACKET SIZE" },

	{ 0x6500, "VOLTAGE FAULT" },

	{ 0x6600, "AUTOMATIC DOCUMENT FEEDER COVER UP {%" },
	{ 0x6601, "AUTOMATIC DOCUMENT FEEDER LIFT UP {%" },
	{ 0x6602, "DOCUMENT JAM IN AUTOMATIC DOCUMENT FEEDER {%" },
	{ 0x6603, "DOCUMENT MISS FEED AUTOMATIC IN DOCUMENT FEEDER {%" },

	{ 0x6700, "CONFIGURATION FAILURE" },
	{ 0x6701, "CONFIGURATION OF INCAPABLE LOGICAL UNITS FAILED" },
	{ 0x6702, "ADD LOGICAL UNIT FAILED" },
	{ 0x6703, "MODIFICATION OF LOGICAL UNIT FAILED" },
	{ 0x6704, "EXCHANGE OF LOGICAL UNIT FAILED" },
	{ 0x6705, "REMOVE OF LOGICAL UNIT FAILED" },
	{ 0x6706, "ATTACHMENT OF LOGICAL UNIT FAILED" },
	{ 0x6707, "CREATION OF LOGICAL UNIT FAILED" },
	{ 0x6708, "ASSIGN FAILURE OCCURRED" },
	{ 0x6709, "MULTIPLY ASSIGNED LOGICAL UNIT" },
	{ 0x670a, "SET TARGET PORT GROUPS COMMAND FAILED" },
	{ 0x670b, "ATA DEVICE FEATURE NOT ENABLED" },
	{ 0x670c, "COMMAND REJECTED" },
	{ 0x670d, "EXPLICIT BIND NOT ALLOWED" },

	{ 0x6800, "LOGICAL UNIT NOT CONFIGURED" },
	{ 0x6801, "SUBSIDIARY LOGICAL UNIT NOT CONFIGURED" },

	{ 0x6900, "DATA LOSS ON LOGICAL UNIT" },
	{ 0x6901, "MULTIPLE LOGICAL UNIT FAILURES" },
	{ 0x6902, "PARITY/DATA MISMATCH" },

	{ 0x6a00, "INFORMATIONAL, REFER TO LOG" },

	{ 0x6b00, "STATE CHANGE HAS OCCURRED" },
	{ 0x6b01, "REDUNDANCY LEVEL GOT BETTER" },
	{ 0x6b02, "REDUNDANCY LEVEL GOT WORSE" },

	{ 0x6c00, "REBUILD FAILURE OCCURRED" },

	{ 0x6d00, "RECALCULATE FAILURE OCCURRED" },

	{ 0x6e00, "COMMAND TO LOGICAL UNIT FAILED" },

	{ 0x6f00, "COPY PROTECTION KEY EXCHANGE FAILURE - AUTHENTICATION FAILURE" },
	{ 0x6f01, "COPY PROTECTION KEY EXCHANGE FAILURE - KEY NOT PRESENT" },
	{ 0x6f02, "COPY PROTECTION KEY EXCHANGE FAILURE - KEY NOT ESTABLISHED" },
	{ 0x6f03, "READ OF SCRAMBLED SECTOR WITHOUT AUTHENTICATION" },
	{ 0x6f04, "MEDIA REGION CODE IS MISMATCHED TO LOGICAL UNIT REGION" },
	{ 0x6f05, "DRIVE REGION MUST BE PERMANENT/REGION RESET COUNT ERROR" },
	{ 0x6f06, "INSUFFICIENT BLOCK COUNT FOR BINDING NONCE RECORDING" },
	{ 0x6f07, "CONFLICT IN BINDING NONCE RECORDING" },
	{ 0x6f08, "INSUFFICIENT PERMISSION" },
	{ 0x6f09, "INVALID DRIVE-HOST PAIRING SERVER" },
	{ 0x6f0a, "DRIVE-HOST PAIRING SUSPENDED" },

	{ 0x7100, "DECOMPRESSION EXCEPTION LONG ALGORITHM ID" },

	{ 0x7200, "SESSION FIXATION ERROR" },
	{ 0x7201, "SESSION FIXATION ERROR WRITING LEAD-IN" },
	{ 0x7202, "SESSION FIXATION ERROR WRITING LEAD-OUT" },
	{ 0x7203, "SESSION FIXATION ERROR - INCOMPLETE TRACK IN SESSION" },
	{ 0x7204, "EMPTY OR PARTIALLY WRITTEN RESERVED TRACK" },
	{ 0x7205, "NO MORE TRACK RESERVATIONS ALLOWED" },
	{ 0x7206, "RMZ EXTENSION IS NOT ALLOWED" },
	{ 0x7207, "NO MORE TEST ZONE EXTENSIONS ARE ALLOWED" },

	{ 0x7300, "CD CONTROL ERROR" },
	{ 0x7301, "POWER CALIBRATION AREA ALMOST FULL" },
	{ 0x7302, "POWER CALIBRATION AREA IS FULL" },
	{ 0x7303, "POWER CALIBRATION AREA ERROR" },
	{ 0x7304, "PROGRAM MEMORY AREA UPDATE FAILURE" },
	{ 0x7305, "PROGRAM MEMORY AREA IS FULL" },
	{ 0x7306, "RMA/PMA IS ALMOST FULL" },
	{ 0x7310, "CURRENT POWER CALIBRATION AREA ALMOST FULL" },
	{ 0x7311, "CURRENT POWER CALIBRATION AREA IS FULL" },
	{ 0x7317, "RDZ IS FULL" },

	{ 0x7400, "SECURITY ERROR" },
	{ 0x7401, "UNABLE TO DECRYPT DATA" },
	{ 0x7402, "UNENCRYPTED DATA ENCOUNTERED WHILE DECRYPTING" },
	{ 0x7403, "INCORRECT DATA ENCRYPTION KEY" },
	{ 0x7404, "CRYPTOGRAPHIC INTEGRITY VALIDATION FAILED" },
	{ 0x7405, "ERROR DECRYPTING DATA" },
	{ 0x7406, "UNKNOWN SIGNATURE VERIFICATION KEY" },
	{ 0x7407, "ENCRYPTION PARAMETERS NOT USEABLE" },
	{ 0x7408, "DIGITAL SIGNATURE VALIDATION FAILURE" },
	{ 0x7409, "ENCRYPTION MODE MISMATCH ON READ" },
	{ 0x740a, "ENCRYPTED BLOCK NOT RAW READ ENABLED" },
	{ 0x740b, "INCORRECT ENCRYPTION PARAMETERS" },
	{ 0x740c, "UNABLE TO DECRYPT PARAMETER LIST" },
	{ 0x740d, "ENCRYPTION ALGORITHM DISABLED" },
	{ 0x7410, "SA CREATION PARAMETER VALUE INVALID" },
	{ 0x7411, "SA CREATION PARAMETER VALUE REJECTED" },
	{ 0x7412, "INVALID SA USAGE" },
	{ 0x7421, "DATA ENCRYPTION CONFIGURATION PREVENTED" },
	{ 0x7430, "SA CREATION PARAMETER NOT SUPPORTED" },
	{ 0x7440, "AUTHENTICATION FAILED" },
	{ 0x7461, "EXTERNAL DATA ENCRYPTION KEY MANAGER ACCESS ERROR" },
	{ 0x7462, "EXTERNAL DATA ENCRYPTION KEY MANAGER ERROR" },
	{ 0x7463, "EXTERNAL DATA ENCRYPTION KEY NOT FOUND" },
	{ 0x7464, "EXTERNAL DATA ENCRYPTION REQUEST NOT AUTHORIZED" },
	{ 0x746e, "EXTERNAL DATA ENCRYPTION CONTROL TIMEOUT" },
	{ 0x746f, "EXTERNAL DATA ENCRYPTION CONTROL ERROR" },
	{ 0x7471, "LOGICAL UNIT ACCESS NOT AUTHORIZED" },
	{ 0x7479, "SECURITY CONFLICT IN TRANSLATED DEVICE" },

	{ 0xffff, "unknown" },
};

/*
 * Status codes.
 */
static struct ptio_val_name ptio_status[] =
{
	{ 0x00,	"GOOD" },
	{ 0x02,	"CHECK CONDITION" },
	{ 0x04,	"CONDITION MET" },
	{ 0x08,	"BUSY" },
	{ 0x18,	"RESERVATION CONFLICT" },
	{ 0x28,	"TASK SET FULL" },
	{ 0x30,	"ACA ACTIVE" },
	{ 0x40,	"TASK ABORTED" },

	{ 0xffff, "unknown" },
};

/*
 * Host status codes.
 */
#define PTIO_DID_OK		0x00 /* No error */
#define PTIO_DID_NO_CONNECT	0x01 /* Couldn't connect before timeout period */
#define PTIO_DID_BUS_BUSY	0x02 /* BUS stayed busy through time out period */
#define PTIO_DID_TIME_OUT	0x03 /* Timed out for other reason */
#define PTIO_DID_BAD_TARGET	0x04 /* Bad target, device not responding? */
#define PTIO_DID_ABORT		0x05 /* Told to abort for some other reason. */
#define PTIO_DID_PARITY		0x06 /* Parity error. */
#define PTIO_DID_ERROR		0x07 /* Internal error detected in the host adapter. */
#define PTIO_DID_RESET		0x08 /* The SCSI bus (or this device) has been reset. */
#define PTIO_DID_BAD_INTR	0x09 /* Got an unexpected interrupt */
#define PTIO_DID_PASSTHROUGH	0x0a /* Forced command past mid-layer. */
#define PTIO_DID_SOFT_ERROR	0x0b /* The low level driver wants a retry. */

static struct ptio_val_name ptio_host_status[] =
{
	{ PTIO_DID_OK,		"DID_OK" },
	{ PTIO_DID_NO_CONNECT,	"DID_NO_CONNECT" },
	{ PTIO_DID_BUS_BUSY,	"DID_BUS_BUSY" },
	{ PTIO_DID_TIME_OUT,	"DID_TIME_OUT" },
	{ PTIO_DID_BAD_TARGET,	"DID_BAD_TARGET" },
	{ PTIO_DID_ABORT,	"DID_ABORT" },
	{ PTIO_DID_PARITY,	"DID_PARITY" },
	{ PTIO_DID_ERROR,	"DID_ERROR" },
	{ PTIO_DID_RESET,	"DID_RESET" },
	{ PTIO_DID_BAD_INTR,	"DID_BAD_INTR" },
	{ PTIO_DID_PASSTHROUGH,	"DID_PASSTHROUGH" },
	{ PTIO_DID_SOFT_ERROR,	"DID_SOFT_ERROR" },

	{ 0xffff, "unknown" },
};

/*
 * Driver status codes.
 */
#define PTIO_DRIVER_OK		0x00
#define PTIO_DRIVER_BUSY	0x01
#define PTIO_DRIVER_SOFT	0x02
#define PTIO_DRIVER_MEDIA	0x03
#define PTIO_DRIVER_ERROR	0x04
#define PTIO_DRIVER_INVALID	0x05
#define PTIO_DRIVER_TIMEOUT	0x06
#define PTIO_DRIVER_HARD	0x07
#define PTIO_DRIVER_SENSE	0x08
#define PTIO_DRIVER_STATUS_MASK	0x0f

static struct ptio_val_name ptio_driver_status[] =
{
	{ PTIO_DRIVER_OK,	"DRIVER_OK" },
	{ PTIO_DRIVER_BUSY,	"DRIVER_BUSY" },
	{ PTIO_DRIVER_SOFT,	"DRIVER_SOFT" },
	{ PTIO_DRIVER_MEDIA,	"DRIVER_MEDIA" },
	{ PTIO_DRIVER_ERROR,	"DRIVER_ERROR" },
	{ PTIO_DRIVER_INVALID,	"DRIVER_INVALID" },
	{ PTIO_DRIVER_TIMEOUT,	"DRIVER_TIMEOUT" },
	{ PTIO_DRIVER_HARD,	"DRIVER_HARD" },
	{ PTIO_DRIVER_SENSE,	"DRIVER_SENSE" },

	{ 0xffff, "unknown" },
};

/*
 * Driver status code flags ('or'ed with code)
 */
#define PTIO_DRIVER_SUGGEST_RETRY	0x10
#define PTIO_DRIVER_SUGGEST_ABORT	0x20
#define PTIO_DRIVER_SUGGEST_REMAP	0x30
#define PTIO_DRIVER_SUGGEST_DIE		0x40
#define PTIO_DRIVER_SUGGEST_SENSE	0x80
#define PTIO_DRIVER_FLAGS_MASK		0xf0

#define ptio_cmd_driver_status(cmd)	((cmd)->io_hdr.driver_status & \
					 PTIO_DRIVER_STATUS_MASK)
#define ptio_cmd_driver_flags(cmd)	((cmd)->io_hdr.driver_status &  \
					 PTIO_DRIVER_FLAGS_MASK)

static const char *ptio_find_val_name(struct ptio_val_name *vals, uint16_t val)
{
	struct ptio_val_name *v = &vals[0];

	while (v->val != 0xffff) {
		if (v->val == val)
			break;
		v++;
	}

	return v->name;
}

static inline const char *ptio_sense_key_str(uint8_t key)
{
        return ptio_find_val_name(ptio_sense_keys, key);
}

static inline const char *ptio_asc_ascq_str(uint16_t asc_ascq)
{
        return ptio_find_val_name(ptio_asc_ascq, asc_ascq);
}

static inline const char *ptio_status_str(uint8_t status)
{
        return ptio_find_val_name(ptio_status, status);
}

static inline const char *ptio_host_status_str(uint8_t status)
{
        return ptio_find_val_name(ptio_host_status, status);
}

static inline const char *ptio_driver_status_str(uint8_t status)
{
        return ptio_find_val_name(ptio_driver_status, status);
}

/*
 * Get command ASC/ASCQ.
 */
static void ptio_get_scsi_sense(struct ptio_cmd *cmd)
{
	unsigned int sense_buf_len = cmd->io_hdr.sb_len_wr;
	uint8_t *sense_buf = cmd->sense_buf;

	if (sense_buf_len < 4) {
		cmd->sense_key = 0;
		cmd->asc_ascq = 0;
		return;
	}

	if ((sense_buf[0] & 0x7F) == 0x72 || (sense_buf[0] & 0x7F) == 0x73) {
		/* store sense key, ASC/ASCQ */
		cmd->sense_key = sense_buf[1] & 0x0F;
		cmd->asc_ascq = ((int)sense_buf[2] << 8) | (int)sense_buf[3];
		return;
	}

	if (sense_buf_len < 14) {
		cmd->sense_key = 0;
		cmd->asc_ascq = 0;
		return;
	}

	if ((sense_buf[0] & 0x7F) == 0x70 || (sense_buf[0] & 0x7F) == 0x71) {
		/* store sense key, ASC/ASCQ */
		cmd->sense_key = sense_buf[2] & 0x0F;
		cmd->asc_ascq = ((int)sense_buf[12] << 8) | (int)sense_buf[13];
	}
}

int ptio_get_sense(struct ptio_dev *dev, struct ptio_cmd *cmd)
{
	if (cmd->io_hdr.status || cmd->io_hdr.host_status != PTIO_DID_OK ||
	    (ptio_cmd_driver_status(cmd) &&
	     (ptio_cmd_driver_status(cmd) != PTIO_DRIVER_SENSE))) {

		if (cmd->io_hdr.host_status == PTIO_DID_TIME_OUT) {
			ptio_dev_err(dev, "SCSI command failed (timeout)\n");
			return -ETIMEDOUT;
		}

		ptio_get_scsi_sense(cmd);

		ptio_dev_err(dev, "SCSI command failed: host status %s, driver status %s\n",
			     ptio_host_status_str(cmd->io_hdr.host_status),
			     ptio_driver_status_str(ptio_cmd_driver_status(cmd)));
		ptio_dev_err(dev, "SCSI command status    : 0x%02x   (%s)\n",
			     cmd->io_hdr.status,
			     ptio_status_str(cmd->io_hdr.status));
		ptio_dev_err(dev, "SCSI command sense key : 0x%02x   (%s)\n",
			     cmd->sense_key,
			     ptio_sense_key_str(cmd->sense_key));
		ptio_dev_err(dev, "SCSI command asc/ascq  : 0x%04x (%s)\n",
			     cmd->asc_ascq,
			     ptio_asc_ascq_str(cmd->asc_ascq));

		return -EIO;
	}

	return 0;
}
